### ISSUE TITLE
problem:[ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]	

### ISSUE THREAD

**Issue by 709505440** [Xilinx/CHaiDNN#105]
[11111_Release.build.log](https://github.com/Xilinx/CHaiDNN/files/2574332/11111_Release.build.log)
![problem](https://user-images.githubusercontent.com/42632274/48385828-f03d6c00-e72a-11e8-94e5-53f4495aad95.png)

**Comment by VishalX** [comment]
@709505440 

The log suggests that the build is successful. Closing.
