### ISSUE TITLE
What's the name of DepthwiseConvolutionLayer in the prototxt?

### ISSUE THREAD

**Issue by Jiaxinging** [Xilinx/CHaiDNN#107]
Hi, does CHaiDNN support Depthwise Convolution Layer? What's the name of Depthwise Convolution Layer in the prototxt?
Thanks!

**Comment by anilmartha** [comment]
Hi @HelloSongRen,

CHaiDNN supports Depthwise Convolution Layer. Caffe uses "Convolution" as the layer type for Depthwise Convolution in the prototxt. We consider a convolution as Depthwise Convolution if its number of outputs and groups are same.

**Comment by Jiaxinging** [comment]
Great! Thank you~ @anilmartha

**Comment by cuongdv1** [comment]
@anilmartha 
I tried to run MobilenetSSD on CHaiDNN and found that all depthwise convolution layers were removed in the function "void XGraphOpt::opt_separable_conv(XGraph *xgraph_opt)". You can check them in the attachment files as below:
**Before removing dw/conv**
![before_optimization](https://user-images.githubusercontent.com/1823583/49132542-64713580-f30f-11e8-881b-69dd48b26f97.png)

**After removing dw/conv**
![after_optimization](https://user-images.githubusercontent.com/1823583/49132541-64713580-f30f-11e8-8ec4-90e13ef4ae59.png)

I understanding that depth-wise conv of MobilenetSSD was not implemented on CHaiDNN?
could you tell me know how to modify CHaiDNN to keep depthwise conv of MobilenetSSD? I am investigating the source code of CHaiDNN, but it's difficult to understanding

Thank you very much.
#117

**Comment by VishalX** [comment]
@cuongdv1, 

#117
With the upcoming release, we are going to support MobileNet-SSD. 

Thanks!

**Comment by mazhongzhong** [comment]
@VishalX,
Do you mean the ChaiDNN doesn't support Depthwise Convolution Layer for the time being? But why anilmartha said the ChaiDNN does support Depthwise Convolution Layer？And the document (https://github.com/Xilinx/CHaiDNN/blob/master/docs/SUPPORTED_LAYERS.md) says so as well.
If the ChaiDNN does support the Depthwise Convolution Layer, why it can not support MobileNet-SSD?
