### ISSUE TITLE
how can i nvme mount ?

### ISSUE THREAD

**Issue by appleeji** [Xilinx/CHaiDNN#11]
I ran chaidnn using the zcu102 board.
For larger data, I'm trying to use an SSD, but the board does not recognize nvme.
I have verified that the lspci command recognizes ssd, but there is no nvme in / dev. Is there a way?

**Comment by VishalX** [comment]
Hi @appleeji,

I don't think there is any way to mount ssd. Please check on Xilinx SDSoC Forums for more. 
Closing issue.
