### ISSUE TITLE
How to run Caffe with Xilinx Quantized model (simulation)?

### ISSUE THREAD

**Issue by eerobert** [Xilinx/CHaiDNN#110]
Would like to know how to run Caffe with Xilinx Quantized model / DynamicFixed model?

Thanks

**Comment by cuongdv1** [comment]
I also would like to know how to run Caffe with Xilinx Quantization that mentioned in PERFORMANCE_SNAPSHOT.md
"Caffe with Xilinx Quantization refers to simulation of Xilinx quantizer using Caffe framework."

Thanks

**Comment by anilmartha** [comment]
Hi @eerobert ,

Quantization of cnns using Xilinx quantization is proprietary scheme by Xilinx . There are plans to put it out part of separate repository. We will keep you post on this.
