### ISSUE TITLE
loop iterator problem

### ISSUE THREAD

**Issue by shinya321** [Xilinx/CHaiDNN#114]
Hi,
I use zcu102, and now I am creating .cpp file following [this](https://github.com/Xilinx/CHaiDNN/blob/master/docs/RUN_NEW_NETWORK.md) to run an original network on the board.
To do so, at first I refer to "ssd_ex.cpp", but I cannot understand what it means as bellow:

ssd_ex.cpp l247-253
<pre>
	//# Run the loop for loop_iter times
	for(int i = 0; i < loop_iter; i++)
	{
		//# Execute the network for input image
		xiExec(chaihandle, input, output);
	}
</pre>

In my thought, it's like "warm-up" process, so processing speed will become stable after we proceed some images.
And in terms of accuracy, no problem even if I change loop_iter from 100 to 1, right?

Sorry to be poor English, it would be greatly appreciated if you could explain the details.
Best regards,
shinya321

**Comment by AnushaPerla** [comment]
Hi @shinya321 

Yes, in terms of accuracy there will be no difference if you change loop_iter from 100 to 1.
