### ISSUE TITLE
How to implement depthwise convolution on CHaiDNN

### ISSUE THREAD

**Issue by cuongdv1** [Xilinx/CHaiDNN#117]
I tried to run MobilenetSSD on CHaiDNN and found that all depthwise convolution layers were removed in the function "void XGraphOpt::opt_separable_conv(XGraph *xgraph_opt)". You can check them in the attachment files as below:
**Before removing dw/conv**
![before_optimization](https://user-images.githubusercontent.com/1823583/49132542-64713580-f30f-11e8-881b-69dd48b26f97.png)

**After removing dw/conv**
![after_optimization](https://user-images.githubusercontent.com/1823583/49132541-64713580-f30f-11e8-8ec4-90e13ef4ae59.png)

I understanding that depth-wise conv of MobilenetSSD was not implemented on CHaiDNN?
could you tell me know how to modify CHaiDNN to keep depthwise conv of MobilenetSSD? I am investigating the source code of CHaiDNN, but it's difficult to understanding

Thank you very much.

**Comment by VishalX** [comment]
See Issue #107
