### ISSUE TITLE
Error in running Estimate Performance in SDSoc

### ISSUE THREAD

**Issue by daichong123** [Xilinx/CHaiDNN#13]
Thanks for providing the program, I have successfully run on the ZCU102 development board.Now I want to run the Estimate Performance in SDSoc, but there is always an error as shown in the following figure. How can I solve it? Thank you!

INFO: [DMAnalysis 83-4494] Analyzing hardware accelerators...
ERROR: [DMAnalysis 83-4430] Performance estimation not supported for "PoolTop". Possible workaround: Consider modifying the loop boundary in the function to be compile-time constant, or use Vivado HLS's tripcount pragma.
Data motion generation exited with return code -3
performance estimation not supported
sds++ log file saved as /home/daichong/Work/SDx_project/CHaiDNN1/Release/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed

![screenshot from 2018-05-14 09-41-36](https://user-images.githubusercontent.com/39259383/39986257-b9c3d8b6-5793-11e8-9bbf-f94a4e8d90e2.png)
![screenshot from 2018-05-14 15-29-52](https://user-images.githubusercontent.com/39259383/39986276-c9b3ff6c-5793-11e8-9a02-7f939617b0ac.png)

**Comment by VishalX** [comment]
Hi @daichong123,

Please check the below link.

https://forums.xilinx.com/t5/SDSoC-Environment-and-reVISION/ERROR-DMAnalysis-83-4429-The-latency-of-hardware-function-quot/td-p/802018
