### ISSUE TITLE
The difference between w/o FC and w/ FC, how to test the w/o FC performance?

### ISSUE THREAD

**Issue by Hugo1994** [Xilinx/CHaiDNN#135]
/home/cyl/Pictures/Screenshot from 2019-01-04 16-16-13.png

I run the official AlexNet and my own AlexNet on the ZCU104, the final performance is only 9.98 images/s, but the official performance snapshot shows the AlexNet is 217 images/s on ZU7. Why?
Please help

**Comment by eerobert** [comment]
Hi, you are not alone

i have zcu104 running alexnet with ~10img/s
but from the performance_snapshot, it seems like it is the expected result.

can you show me where you have the number 217img/s?

**Comment by Hugo1994** [comment]
> Hi, you are not alone
> 
> i have zcu104 running alexnet with ~10img/s
> but from the performance_snapshot, it seems like it is the expected result.
> 
> can you show me where you have the number 217img/s?

the official performance snapshot shows the w/o AlexNet is 217 images/s while w/ AlexNet is 10 images/s on ZU7.  why performance varies so much? what is the difference between?

**Comment by NeutrinoXY** [comment]
Hi,

The reason is pretty simple. Since the 2.0 version, the fully connected layer runs on processor, so the performance on this layer is much degraded compared to its HW version. However, the accelerator can now runs on two different subgraphs in parallel, so at the end you gain in overall speed if your fully connected layers represent a small part of your network in terms of computational complexity.

That's the case for GoogleNet, but not for AlexNet, and it explains why you get those numbers. In the official snapshot, it also gives performances "without fc". It is just the speed on the first part of the graph that runs on hardware, it's a good indication of the accelerator's performance for convolutional operations.

**Comment by Hugo1994** [comment]
> Hi,
> 
> The reason is pretty simple. Since the 2.0 version, the fully connected layer runs on processor, so the performance on this layer is much degraded compared to its HW version. However, the accelerator can now runs on two different subgraphs in parallel, so at the end you gain in overall speed if your fully connected layers represent a small part of your network in terms of computational complexity.
> 
> That's the case for GoogleNet, but not for AlexNet, and it explains why you get those numbers. In the official snapshot, it also gives performances "without fc". It is just the speed on the first part of the graph that runs on hardware, it's a good indication of the accelerator's performance for convolutional operations.

Thank you for your answer. I still have some question.
1. The previous paper has proved that CONV-layers is compute-intensive while the FC-layers is memory-intensive. Now that the performance on this layer is much degraded compared to its HW version, why not put all layers except softmax onto the FPGA?
2. In the official snapshot, it also gives performances "without fc" (FPGA) and "within fc"(ARM + FPGA), it can only denote that FC-layer in the ARM is very time-huangry, it's not a enough indication of the accelerator's performance for convolutional operations. Am i reading this correctly?

**Comment by xiemark** [comment]
CHaiDNN-master\software\scheduler\xi_scheduler.cpp line from 370 to 394
#if 0
					//# Call FC wrapper
					FcForward(
							(CHAR_TYPE*)hwQueue[ImgId][whichFc].wts_ptrs[0],
							(CHAR_TYPE*)hwQueue[ImgId][whichFc].wts_ptrs[1],
							(SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[0],
							(SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[1],
							(SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[2],
							(SHORT_TYPE *)hwQueue[ImgId][whichFc].bias_ptr,
							(SHORT_TYPE *)hwQueue[ImgId][whichFc].out_ptrs[0],
							(INT_TYPE*)hwQueue[ImgId][whichFc].params);
#endif


					//# Call FC wrapper
					SwFcForward(
							(IO_DATA_TYPE*)hwQueue[0][whichFc].in_ptrs[0],
							(IO_DATA_TYPE*)hwQueue[0][whichFc].in_ptrs[1],
							(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].in_ptrs[2],
							(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].wts_ptrs[0],
							(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].bias_ptr,
							(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].out_ptrs[0],
							(INT_TYPE *)hwQueue[0][whichFc].params
					);

They use SwFcForward instead of FcForward.

**Comment by Hugo1994** [comment]
> CHaiDNN-master\software\scheduler\xi_scheduler.cpp line from 370 to 394
> #if 0
> //# Call FC wrapper
> FcForward(
> (CHAR_TYPE*)hwQueue[ImgId][whichFc].wts_ptrs[0],
> (CHAR_TYPE*)hwQueue[ImgId][whichFc].wts_ptrs[1],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[0],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[1],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[2],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].bias_ptr,
> (SHORT_TYPE _)hwQueue[ImgId][whichFc].out_ptrs[0], (INT_TYPE_)hwQueue[ImgId][whichFc].params);
> #endif
> 
> ```
> 				//# Call FC wrapper
> 				SwFcForward(
> 						(IO_DATA_TYPE*)hwQueue[0][whichFc].in_ptrs[0],
> 						(IO_DATA_TYPE*)hwQueue[0][whichFc].in_ptrs[1],
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].in_ptrs[2],
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].wts_ptrs[0],
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].bias_ptr,
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].out_ptrs[0],
> 						(INT_TYPE *)hwQueue[0][whichFc].params
> 				);
> ```
> They use SwFcForward instead of FcForward.
Do you know  how to test the w/o FC performance?

**Comment by NeutrinoXY** [comment]
@linpeng

1. Because it's optimized for GoogleNet. If you want to run AlexNet, you should probably implement the HW function of the fully connected layer, and use it for the two first FC layers, and then run last FC and softmax layers on SW in parallel.

2. Yes.

**Comment by Hugo1994** [comment]
> CHaiDNN-master\software\scheduler\xi_scheduler.cpp line from 370 to 394
> #if 0
> //# Call FC wrapper
> FcForward(
> (CHAR_TYPE*)hwQueue[ImgId][whichFc].wts_ptrs[0],
> (CHAR_TYPE*)hwQueue[ImgId][whichFc].wts_ptrs[1],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[0],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[1],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].in_ptrs[2],
> (SHORT_TYPE *)hwQueue[ImgId][whichFc].bias_ptr,
> (SHORT_TYPE _)hwQueue[ImgId][whichFc].out_ptrs[0], (INT_TYPE_)hwQueue[ImgId][whichFc].params);
> #endif
> 
> ```
> 				//# Call FC wrapper
> 				SwFcForward(
> 						(IO_DATA_TYPE*)hwQueue[0][whichFc].in_ptrs[0],
> 						(IO_DATA_TYPE*)hwQueue[0][whichFc].in_ptrs[1],
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].in_ptrs[2],
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].wts_ptrs[0],
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].bias_ptr,
> 						(SW_FC_DATA_TYPE *)hwQueue[0][whichFc].out_ptrs[0],
> 						(INT_TYPE *)hwQueue[0][whichFc].params
> 				);
> ```
> They use SwFcForward instead of FcForward.

@xiemark I am not sure what exactly you mean. FcForward is replaced by SwFcForward, it is explained for within or without FC, right? Do you know how to test the w/o FC performance?

**Comment by xiemark** [comment]
@xiemark I am not sure what exactly you mean. FcForward is replaced by SwFcForward, it is explained for within or without FC, right? Do you know how to test the w/o FC performance?

FC is calculated by software now. So your test is done by sofware FC without hardware FC.

**Comment by Hugo1994** [comment]
> @xiemark I am not sure what exactly you mean. FcForward is replaced by SwFcForward, it is explained for within or without FC, right? Do you know how to test the w/o FC performance?
> 
> FC is calculated by software now. So your test is done by sofware FC without hardware FC.

Thanks for your reply.  I got it.  I have another problem in  #136  Do you know how to test the w/o FC performance?

**Comment by VishalX** [comment]
Check #136.
Closing
