### ISSUE TITLE
The official example and inference run is explained for w/ FC CNN, How to test the w/o FC performance?

### ISSUE THREAD

**Issue by Hugo1994** [Xilinx/CHaiDNN#136]
Take AlexNet as example, the official AlexNet example is 9.98 images/s for w/ FC, but how to test the w/o FC 217 image/s ?

**Comment by NeutrinoXY** [comment]
If I remember well, you can use the getPerfInfo function defined in software/xi_interface.cpp.

**Comment by Hugo1994** [comment]
> If I remember well, you can use the getPerfInfo function defined in software/xi_interface.cpp.

Thanks for your reply, I am trying, can you speak more clearly?

**Comment by VishalX** [comment]
@linpeng9527,

To check the performance of AlexNet w/o FC layers, the simplest way is to remove the FC layers from your prototxt and don't use graph splitting.

**Comment by Hugo1994** [comment]
> @linpeng9527,
> 
> To check the performance of AlexNet w/o FC layers, the simplest way is to remove the FC layers from your prototxt and don't use graph splitting.

@VishalX Thanks, I will do as you said, removing the FC layers from  prototxt.  but what does your "don't use graph splitting" mean?

**Comment by Hugo1994** [comment]
> @linpeng9527,
> 
> To check the performance of AlexNet w/o FC layers, the simplest way is to remove the FC layers from your prototxt and don't use graph splitting.

@VishalX  Hi，I do what as you said, removing the FC layers from prototxt, but i encounter a problem. the log is as follows.
root@zcu104:/mnt# ./sdx_alexnet.elf Xilinx 8 images/camel.jpg images/goldfish.JP
EG
[INFOx] Network Path : models/AlexNet/8Bit
[PARSE] Parsing conv1
[PARSE] Parsing relu1
[PARSE] Parsing pool1
[PARSE] Parsing conv2
[PARSE] Parsing relu2
[PARSE] Parsing pool2
[PARSE] Parsing conv3
[PARSE] Parsing relu3
[PARSE] Parsing conv4
[PARSE] Parsing relu4
[PARSE] Parsing conv5
[PARSE] Parsing relu5
[PARSE] Parsing pool5
[libprotobuf INFO google/protobuf/io/coded_stream.cc:610] Reading dangerously la
rge protocol message.  If the message turns out to be larger than 2147483647 byt
es, parsing will be halted for security reasons.  To increase the limit (or to d
isable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/pro
tobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of
bytes read was 243862633
[IG001] Extracting conv1 weights ...
[IG001] Extracting conv1 bias ...
[IG001] Extracting conv2 weights ...
[IG001] Extracting conv2 bias ...
[IG001] Extracting conv3 weights ...
[IG001] Extracting conv3 bias ...
[IG001] Extracting conv4 weights ...
[IG001] Extracting conv4 bias ...
[IG001] Extracting conv5 weights ...
[IG001] Extracting conv5 bias ...
[INFOx] Graph generated
[INFOx] Generating JobQueue
[INFOx] JobQueue generated
[INFOx] Creating Memory


[INFOx] Memory created
[INFOx] Network Path : models/AlexNet/8Bit

[INFOx] Init Start : This may take a while ...
[INFOx] Init Done
[PARSE] Parsing conv1
[PARSE] Parsing relu1
[PARSE] Parsing pool1
[PARSE] Parsing conv2
[PARSE] Parsing relu2
[PARSE] Parsing pool2
[P[  167.286139] FAT-fs (mmcblk0p1): error, fat_free_clusters: deleting FAT entr
y beyond EOF
ARSE] Parsing conv3
[PARSE] Parsing relu3
[PARSE] Parsing conv[  167.294667] FAT-fs (mmcblk0p1): Filesystem has been set r
ead-only
4
[PARSE] Parsing relu4
[PARSE] Parsing conv5
[PARSE] Parsing relu5
[PARSE] Parsing pool5
[EP301] Couldn't find specified start layer : fc6

**Comment by Hugo1994** [comment]
> If I remember well, you can use the getPerfInfo function defined in software/xi_interface.cpp.

@NeutrinoXY I got error when I simply removed  FC layers from prototxt. I will be appreciate it if you explain testing the "w/o FC performance" more clearly.

**Comment by VishalX** [comment]
@linpeng9527 

If you see the [alexnet_ex.cpp](https://github.com/Xilinx/CHaiDNN/blob/master/software/example/alexnet_ex.cpp),

```
	//# start/end layer in the graph1
	string start_layer_graph1 = "";
	string end_layer_graph1   = "pool5";

	//# start/end layer in the graph2
	string start_layer_graph2 = "fc6";
	string end_layer_graph2   = "";

	//# Flag indicate layer1 or not
	//# 1 - if image data is the for first layer input otherwise 0
	bool is_first_layer_g1 = 1;
	bool is_first_layer_g2 = 0;

	//# Number of images to process
	//# Supported batch size is 2
	int numImg_to_process = 2;

	//# Struct which holds the input/output layer info
	io_layer_info io_layer_info_ptr1;
	io_layer_info io_layer_info_ptr2;

	//####### Init call for graph1
	void *chaihandle1 = xiInit(dirpath, prototxt, caffemodel, &io_layer_info_ptr1,
			numImg_to_process, is_first_layer_g1, start_layer_graph1, end_layer_graph1);


	//####### Init call for graph2
	void *chaihandle2 = xiInit(dirpath, prototxt, caffemodel, &io_layer_info_ptr2,
			numImg_to_process, is_first_layer_g2, start_layer_graph2, end_layer_graph2);
```
The network is splitted into 2 graphs (graph1 & graph2). Now, as you have removed the FC layers, you don't require graph2 at all and only need to initialize graph1 (`chaihandle1`).

See the [ssd_ex.cpp](https://github.com/Xilinx/CHaiDNN/blob/master/software/example/ssd_ex.cpp) which doesn't use graph splitting and make the necessary changes in your example file.

**Comment by Hugo1994** [comment]
> @linpeng9527
> 
> If you see the [alexnet_ex.cpp](https://github.com/Xilinx/CHaiDNN/blob/master/software/example/alexnet_ex.cpp),
> 
> ```
> 	//# start/end layer in the graph1
> 	string start_layer_graph1 = "";
> 	string end_layer_graph1   = "pool5";
> 
> 	//# start/end layer in the graph2
> 	string start_layer_graph2 = "fc6";
> 	string end_layer_graph2   = "";
> 
> 	//# Flag indicate layer1 or not
> 	//# 1 - if image data is the for first layer input otherwise 0
> 	bool is_first_layer_g1 = 1;
> 	bool is_first_layer_g2 = 0;
> 
> 	//# Number of images to process
> 	//# Supported batch size is 2
> 	int numImg_to_process = 2;
> 
> 	//# Struct which holds the input/output layer info
> 	io_layer_info io_layer_info_ptr1;
> 	io_layer_info io_layer_info_ptr2;
> 
> 	//####### Init call for graph1
> 	void *chaihandle1 = xiInit(dirpath, prototxt, caffemodel, &io_layer_info_ptr1,
> 			numImg_to_process, is_first_layer_g1, start_layer_graph1, end_layer_graph1);
> 
> 
> 	//####### Init call for graph2
> 	void *chaihandle2 = xiInit(dirpath, prototxt, caffemodel, &io_layer_info_ptr2,
> 			numImg_to_process, is_first_layer_g2, start_layer_graph2, end_layer_graph2);
> ```
> The network is splitted into 2 graphs (graph1 & graph2). Now, as you have removed the FC layers, you don't require graph2 at all and only need to initialize graph1 (`chaihandle1`).
> 
> See the [ssd_ex.cpp](https://github.com/Xilinx/CHaiDNN/blob/master/software/example/ssd_ex.cpp) which doesn't use graph splitting and make the necessary changes in your example file.

@VishalX  Thanks for your advice. I changed the alexnet_ex.cpp as you said, but the performance is only 90 images/s. There is certain gap compared with offocial 217 images/s. Do you know the potential cause? The performance is as follows
![image](https://user-images.githubusercontent.com/30885465/51291270-8189d100-1a41-11e9-82f8-7021b84a9321.png)
**
[alexnet_wo_fc.cpp.tar.gz](https://github.com/Xilinx/CHaiDNN/files/2766939/alexnet_wo_fc.cpp.tar.gz)
**

**Comment by VishalX** [comment]
@linpeng9527 

Can you share the design config, device, and frequency details?

**Comment by Hugo1994** [comment]
> @linpeng9527
> 
> Can you share the design config, device, and frequency details?

@VishalX  Thanks for your reply. I build the project in SDx 2018.2 followed by official "Creating SDx GUI Project".
The device is KCU104 evalulation board. The frequency is 200MHz, The configure in “xi_conv_config.h” is as follows, so is "hw_settings.h".
1. 
//**** URAM ENABLE FLAGS FOR THE BUFFERS
#define XI_BIAS_URAM_EN 	0
#define XI_WTS_URAM_EN 	1
#define XI_ISTG_URAM_EN 	1
#define XI_OSTG_URAM_EN 	1
#define XI_FEED_URAM_EN 	0
#define XI_SCALE_URAM_EN 	0

//**** CONFIGURABLE MACROS
#if XI_DIET_CHAI_Z || XI_DIET_CHAI_ZUPLUS
#define XI_KER_PROC       	16
#define XI_PIX_PROC       	16
#define XI_ISTAGEBUFF_DEPTH 1024
#define XI_OSTAGEBUFF_DEPTH 1024
#define XI_WEIGHTBUFF_DEPTH 1024
#else
#define XI_KER_PROC       	16
#define XI_PIX_PROC       	16
#define XI_ISTAGEBUFF_DEPTH 8192
#define XI_OSTAGEBUFF_DEPTH 2048
#define XI_WEIGHTBUFF_DEPTH 2048	
#endif
2.
 POOL_ENABLE and DECONV_ENABLE are set to 0.

The w/ FC performance for AlexNet is 9 images/s，The w/o FC performance for AlexNet is 89 images/s.
Have I omitted anything?

**Comment by VishalX** [comment]
@linpeng9527 

Set below environment variable,
```
export OPENBLAS_NUM_THREADS=3
```
Run
```
./<executable>.elf Xilinx 8 images/camel.jpg images/goldfish.JPEG
```

**Comment by Hugo1994** [comment]
@VishalX 
The w/ FC performance for alexnet is 9 images/s and w/o FC performance is 89 images/s. It is all tested in the configure OPENBLAS_NUM_THREADS=3. When i set OPENBLAS_NUM_THREADS=2, the w/ FC is 6 images/s while the w/o FC is also 89 images/s. There is little performance difference in w/o FC

**Comment by VishalX** [comment]
@linpeng9527 

The performance numbers quoted [here](https://github.com/Xilinx/CHaiDNN/blob/master/docs/PERFORMANCE_SNAPSHOT.md) for zu7 device are at 300/600 MHz. You are running at 200 MHz. This is one definite reason for the lower performance for your build. 

Could you also share the timing reports (mentioned below), so that we can confirm?
```
zcu104_wrapper_timing_summary_routed.rpt
zcu104_wrapper_utilization_placed.rpt
```
You can find them inside
```
_sds/p0/vivado/prj/prj.runs/impl_1 
```

**Comment by Hugo1994** [comment]
> @linpeng9527
> 
> The performance numbers quoted [here](https://github.com/Xilinx/CHaiDNN/blob/master/docs/PERFORMANCE_SNAPSHOT.md) for zu7 device are at 300/600 MHz. You are running at 200 MHz. This is one definite reason for the lower performance for your build.
> 
> Could you also share the timing reports (mentioned below), so that we can confirm?
> 
> ```
> zcu104_wrapper_timing_summary_routed.rpt
> zcu104_wrapper_utilization_placed.rpt
> ```
> You can find them inside
> 
> ```
> _sds/p0/vivado/prj/prj.runs/impl_1 
> ```

@VishalX Thanks for your reply. The timing reports you mentioned is as follows.
[zcu104_wrapper_timing_summary_routed.rpt.tar.gz](https://github.com/Xilinx/CHaiDNN/files/2767385/zcu104_wrapper_timing_summary_routed.rpt.tar.gz)
[zcu104_wrapper_utilization_placed.rpt.tar.gz](https://github.com/Xilinx/CHaiDNN/files/2767386/zcu104_wrapper_utilization_placed.rpt.tar.gz)

I will try to improve the frequency. I always don't understand why there is two frequency 300MHz/600MHz, what does it mean, respectively?

**Comment by Hugo1994** [comment]
> This is one definite reason for the lower performance for your build.

@VishalX  Hi, I will try to improve the frequency, but I don't think the frequency is the main reason. Because my 200MHz w/ FC performance 9 images/s is very similar to the official 300/600MHz 9.99 images/s. I am verifying this guess.

**Comment by VishalX** [comment]
@linpeng9527 

By looking at your timing report, it seems you built the design at **100/200 MHz**, not at 200/400 MHz.

There are two frequencies because the compute DSPs are running at twice the frequency as that of the rest of the logic.

To build for 200/400 or 300/600 MHz, change the below in SDS++Compiler settings,

sds++ -sds-hw XiConvolutionTop  <path to design>/conv/src/xi_convolution_top.cpp -clkid **CLKID** -hls-tcl  <path to design>/conv/scripts/config_core.tcl -sds-end

Where, 
```
CLKID=3 for 200/400 MHz
CLKID=4 for 300/600 MHz
```
These are applicable for stock platforms. Also, make sure to set the Datamotion Clock Frequency accordingly in SDx GUI.

**Comment by VishalX** [comment]
w/ FC performance will be similar for different frequencies because FC layers run on PS (ARM) and not on  PL. As FC layers' latency is very high, the overall impact on performance will be very less at lower frequencies.

**Comment by Hugo1994** [comment]
> @linpeng9527
> 
> By looking at your timing report, it seems you built the design at **100/200 MHz**, not at 200/400 MHz.
> 
> There are two frequencies because the compute DSPs are running at twice the frequency as that of the rest of the logic.
> 
> To build for 200/400 or 300/600 MHz, change the below in SDS++Compiler settings,
> 
> sds++ -sds-hw XiConvolutionTop /conv/src/xi_convolution_top.cpp -clkid **CLKID** -hls-tcl /conv/scripts/config_core.tcl -sds-end
> 
> Where,
> 
> ```
> CLKID=3 for 200/400 MHz
> CLKID=4 for 300/600 MHz
> ```
> These are applicable for stock platforms. Also, make sure to set the Datamotion Clock Frequency accordingly in SDx GUI.

@VishalX Thank you very so much for your patient assistance. There are some thing I didn't get right before.  I set the Datamotion Clock Frequency accordingly in SDx GUI 200MHz, so I think the work frequency is 200MHz. I am wrong. 
![image](https://user-images.githubusercontent.com/30885465/51302186-a182ba00-1a6c-11e9-904b-db7864502f4a.png)

I will change the frequency as you said. Thank you.

**Comment by Hugo1994** [comment]
@VishalX  Everything runs OK, you can close this. Thank you very much

**Comment by averr5** [comment]
@NeutrinoXY I am running AlexNet on the  board and got performance in images/s. Now how do i use getPerfInfo function?
