### ISSUE TITLE
build failure zcu102

### ISSUE THREAD

**Issue by Jwy-jump** [Xilinx/CHaiDNN#138]
@@stsoe  ProciStg_Loop:
           @@@^~~~~~~~~~~~~~
Performing accelerator source linting for XiConvolutionTop
Performing pragma generation
INFO: [PragmaGen 83-3231] Successfully generated tcl script: /home/jwy/workspace/chaindnn/Release/_sds/vhls/XiConvolutionTop.tcl
Moving function XiConvolutionTop to Programmable Logic
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling '/home/jwy/SDx/Vivado/2018.2/bin/vivado_hls /home/jwy/workspace/chaindnn/Release/_sds/vhls/XiConvolutionTop_run.tcl -l XiConvolutionTop_vivado_hls.log'
make: *** [src/design/conv/src/xi_convolution_top.o] Error 1
sds++ log file saved as /home/jwy/workspace/chaindnn/Release/_sds/reports/sds_xi_convolution_top.log
ERROR: [SdsCompiler 83-5004] Build failed

src/design/conv/src/subdir.mk:18: recipe for target 'src/design/conv/src/xi_convolution_top.o' failed

**Comment by Jwy-jump** [comment]
@denolf @stsoe @KarstenTrott @kamranjk

**Comment by VishalX** [comment]
@JIAWENYANG,

Please share the log.

**Comment by Jwy-jump** [comment]
@VishalX 
[sds_xi_deconv_top.log](https://github.com/Xilinx/CHaiDNN/files/2744635/sds_xi_deconv_top.log)

**Comment by Jwy-jump** [comment]
[chaindnn_Release.build.log](https://github.com/Xilinx/CHaiDNN/files/2744646/chaindnn_Release.build.log)
@VishalX ,thanks ！

**Comment by VishalX** [comment]
From **sds_xi_deconv_top.log**,
```
INFO: [IMPL 213-8] Exporting RTL as a Vivado IP.
TclStackFree: incorrect freePtr. Call out of sequence?

****** Vivado v2018.2 (64-bit)
  **** SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
  **** IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
    ** Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.

Abnormal program termination (6)
Please check '/home/jwy/workspace/chaindnn/Release/_sds/vhls/XiDeconvTop/solution/impl/ip/hs_err_pid60484.log' for details.
```
Please check the above log too. It seems to be a tool issue. Check the below link if that helps.
https://forums.xilinx.com/t5/Synthesis/TclStackFree-incorrect-freePtr-Call-out-of-sequence/td-p/423929

**Comment by JIAWENYANG** [comment]
thanks,the logs are as flow:
  @VishalX [hs_err_pid60484.log](https://github.com/Xilinx/CHaiDNN/files/2745781/hs_err_pid60484.log)

**Comment by Jwy-jump** [comment]
@VishalX 
I rebuilt many times,ERROR: [VPL 60-704] Integration error, One or more synthesis runs failed during dynamic region dcp generation
ERROR: [VPL 60-806] Failed to finish platform linker
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling '/home/jwy/SDx/SDx/2018.2/bin/vpl --iprepo /home/jwy/workspace/chaindnn/Release/_sds/iprepo/repo --iprepo /home/jwy/SDx/SDx/2018.2/data/ip/xilinx --platform /home/jwy/SDx/SDx/2018.2/platforms/zcu102/zcu102.xpfm --temp_dir /home/jwy/workspace/chaindnn/Release/_sds/p0 --output_dir /home/jwy/workspace/chaindnn/Release/_sds/p0/vpl --input_file /home/jwy/workspace/chaindnn/Release/_sds/p0/.xsd/top.bd.tcl --target hw --save_temps --kernels PoolTop:XiDeconvTop:XiConvolutionTop:adapter --webtalk_flag SDSoC --remote_ip_cache /home/jwy/workspace/ip_cache --xp "param:compiler.skipTimingCheckAndFrequencyScaling=1" --xp "vivado_prop:run.impl_1.{STEPS.OPT_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.impl_1.{STEPS.PLACE_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.impl_1.STEPS.PHYS_OPT_DESIGN.IS_ENABLED=1" --xp "vivado_prop:run.impl_1.{STEPS.PHYS_OPT_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.impl_1.{STEPS.ROUTE_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.synth_1.{STEPS.SYNTH_DESIGN.TCL.PRE}={/home/jwy/workspace/chaindnn/src/design/conv/scripts/mcps.tcl}" --xp "vivado_prop:run.impl_1.{STEPS.PLACE_DESIGN.TCL.PRE}={/home/jwy/workspace/chaindnn/src/design/conv/scripts/mcps.tcl}" --xp "param:compiler.deleteDefaultReportConfigs=false" '
sds++ log file saved as /home/jwy/workspace/chaindnn/Release/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed
sds++ completed at Sat Jan 12 08:11:15 PST 2019
[sds.log](https://github.com/Xilinx/CHaiDNN/files/2753806/sds.log)
[chaindnn_Release.build.log](https://github.com/Xilinx/CHaiDNN/files/2753808/chaindnn_Release.build.log)

**Comment by Jwy-jump** [comment]
@ @VishalX 
Sorry, but it appears that a Xilinx program has terminated unexpectedly. Please contact Xilinx technical support for further assistance and give them the contents of 
[hs_err_pid47847.log](https://github.com/Xilinx/CHaiDNN/files/2754157/hs_err_pid47847.log)

[chaindnn_Release.build.log](https://github.com/Xilinx/CHaiDNN/files/2754150/chaindnn_Release.build.log)
