### ISSUE TITLE
Build of software not happening in 2018.3 for ZCU102 platform

### ISSUE THREAD

**Issue by NP95** [Xilinx/CHaiDNN#144]
So after #141  where I was able to build the hardware sucessfully, I tried to build software but I am runnning into errors which are hard to debug.  I have attached the Makefile and error logs, This is on Ubuntu 18.04 LTS with SDSoc 2018.3

[Logs.zip](https://github.com/Xilinx/CHaiDNN/files/2821278/Logs.zip)

**Comment by VishalX** [comment]
@NP95 
This looks like a compiler issue to me, something to do with GLIBC. Did you build the hardware with the same version of SDSoC?
