### ISSUE TITLE
Error while building CHaiDNN software

### ISSUE THREAD

**Issue by averr5** [Xilinx/CHaiDNN#149]
I have already built the hardware. Now I am trying to build the software following Build from source using the Makefile and I jump into the following errors : 

[errors.txt](https://github.com/Xilinx/CHaiDNN/files/2889045/errors.txt)

Any idea how to overcome these errors ?

**Comment by VishalX** [comment]
It's because sds_lib.h not getting included. Make sure to set the correct SDx path in Makefile. 
 
An alternate way is to set the value of below macro to 0 in [scheduler.hpp](https://github.com/Xilinx/CHaiDNN/blob/master/software/scheduler/xi_scheduler.hpp).
#define LAYERWISE_PERFORMANCE

**Comment by averr5** [comment]
I gave the right SDx path and I am trying to build the software again.
I am facing new errors now.
[error.txt](https://github.com/Xilinx/CHaiDNN/files/2894735/error.txt)

**Comment by averr5** [comment]
@VishalX Any idea about the errors ?

**Comment by VishalX** [comment]
`/../lib/gcc/aarch64-linux-gnu/7.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lxlnxdnn`

As you can see, it is not able to find the **libxlnxdnn.so** library. This .so is generated when you build the hardware. Review the path for this lib in your Makefile.

**Comment by averr5** [comment]
I got the software build. I missed to copy libparser_arm.so, libxlnxdnn.so, libxstack.so files from SD_Card/zcu102/lib to SD_Card/lib

**Comment by gitosu67** [comment]
@VishalX I gave the right installation path of SDx in the Makefile but still notice the same issue. how to fix it?
