### ISSUE TITLE
New project

### ISSUE THREAD

**Issue by Anjali-iit8** [Xilinx/CHaiDNN#17]
Hi,
I have a project involving image processing and neural networks which I want to port to Xilinx platform zcu104_rv_ss. It was made using LeNet and I have successfully got the executable file for the same. Now I have a main code for which I want to get the elf file. Can you help me with that as I am unable to find any documentation regarding that.

Thanks,
Anjali

**Comment by NeutrinoXY** [comment]
Hello,

I don't understand your issue. Can you be more specific ? What is your "main code" you want to get the .elf file from ?

Best regards.

**Comment by Anjali-iit8** [comment]
Hello,
I have a project implemented using OpenCV and caffe packages. It is a classification project. I have trained the model using LeNet. Now I want to port it to the FPGA for which I want to convert it so that I can transfer it to the SD-Card for bootup.

Thanks,

**Comment by Anjali-iit8** [comment]
@NeutrinoXY  Hello, can I also execute these examples given in the repository as well as my my project using the zcu104 platform?

Thanks

**Comment by VishalX** [comment]
CHaiDNN-v2 supports zcu104 platform. Please try the latest release.
