### ISSUE TITLE
Using Vitis to run ChaiDNN

### ISSUE THREAD

**Issue by nivi1501** [Xilinx/CHaiDNN#181]
Hi, 
   Can you please share how to run ChaiDNN using Vitis tool? Vitis includes the functionality which was supported by SDSoc. Do I need to make significant changes in the code?

Regards,
Nivedita

**Comment by sumitn-xilinx** [comment]
ChaiDNN is not being worked upon for many years now. It was never built with Vitis. 
If you happen to try it out and face any issues, please feel free to post it on the Vitis support forum.

**Comment by nivi1501** [comment]
Ok, thanks a lot for the reply.
I just want to print statements in the console regarding which layer is getting executed. I do not care about synthesis and implementation results. Can you share fastest way to implement this using SDSoC development environment?

**Comment by VishalX** [comment]
@nivi1501 There is one compile-time option that can be used to enable console logging. The scheduler already has all the messages.
Just build the software code with ENABLE_CONSOLE_TEXT macro enabled.

https://github.com/Xilinx/CHaiDNN/blob/master/software/scheduler/xi_scheduler.cpp#L521

Also, you can add custom messages as required.

**Comment by nivi1501** [comment]
Thanks a lot.
