### ISSUE TITLE
Build failed, can anyone help?

### ISSUE THREAD

**Issue by HelloSongRen** [Xilinx/CHaiDNN#21]
Hi,
I am trying to build ChaiDNN with Ubuntu 16.04, but I get sds.log this:

...
[03:10:16] Phase 10 Post Router Timing
[03:10:16] Finished 5th of 6 tasks (FPGA routing). Elapsed time: 00h 36m 01s 

[03:10:16] Starting bitstream generation..

ERROR: [VPL 60-704] Integration error, problem implementing dynamic region, write_bitstream ERROR
ERROR: [VPL 60-806] Failed to finish platform linker
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling '/home/ssssspe/FPGA/SDx/2017.4/bin/vpl  --iprepo /home/ssssspe/song/FPGA/CHaiDNN/design/scripts/kernel/_sds/iprepo/repo  --iprepo /home/ssssspe/FPGA/SDx/2017.4/data/ip/xilinx  --platform /home/ssssspe/FPGA/SDx/2017.4/platforms/zcu102/zcu102.xpfm  --temp_dir /home/ssssspe/song/FPGA/CHaiDNN/design/scripts/kernel/_sds/p0  --output_dir /home/ssssspe/song/FPGA/CHaiDNN/design/scripts/kernel/_sds/p0/vpl  --input_file /home/ssssspe/song/FPGA/CHaiDNN/design/scripts/kernel/_sds/p0/.xsd/top.bd.tcl  --target hw   --save_temps  --kernels XiConvolutionTop:PoolTop:xiSgemvTop:XiDeconvTop --webtalk_flag SDSoC  --xp "param:compiler.skipTimingCheckAndFrequencyScaling=1" '
sds++ log file saved as /home/ssssspe/song/FPGA/CHaiDNN/design/scripts/kernel/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed
sds++ completed at Tue May 29 04:39:02 CST 2018
**********************************************************************************************
the vivado.log:

...
Finished Running Vector-less Activity Propagation
102 Infos, 3 Warnings, 1 Critical Warnings and 0 Errors encountered.
report_power completed successfully
report_power: Time (s): cpu = 00:08:03 ; elapsed = 00:27:16 . Memory (MB): peak = 12192.148 ; gain = 322.953 ; free physical = 171 ; free virtual = 830
INFO: [runtcl-4] Executing : report_route_status -file updated_full_design_route_status.rpt -pb updated_full_design_route_status.pb
report_route_status: Time (s): cpu = 00:00:05 ; elapsed = 00:03:03 . Memory (MB): peak = 12192.148 ; gain = 0.000 ; free physical = 223 ; free virtual = 830
INFO: [runtcl-4] Executing : report_timing_summary -max_paths 10 -file updated_full_design_timing_summary_routed.rpt -rpx updated_full_design_timing_summary_routed.rpx -warn_on_violation 
INFO: [Timing 38-91] UpdateTimingParams: Speed grade: -2, Temperature grade: E, Delay Type: min_max.
INFO: [Timing 38-191] Multithreading enabled for timing update using a maximum of 4 CPUs
CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.
report_timing_summary: Time (s): cpu = 00:00:53 ; elapsed = 00:02:11 . Memory (MB): peak = 12319.141 ; gain = 126.992 ; free physical = 359 ; free virtual = 732
INFO: [runtcl-4] Executing : report_incremental_reuse -file updated_full_design_incremental_reuse_routed.rpt
INFO: [Vivado_Tcl 4-545] No incremental reuse to report, no incremental placement and routing data was found.
INFO: [runtcl-4] Executing : report_clock_utilization -file updated_full_design_clock_utilization_routed.rpt
report_clock_utilization: Time (s): cpu = 00:01:26 ; elapsed = 00:02:13 . Memory (MB): peak = 12319.141 ; gain = 0.000 ; free physical = 217 ; free virtual = 706
Command: write_bitstream -force zcu102_wrapper.bit
Attempting to get a license for feature 'Implementation' and/or device 'xczu9eg'
INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xczu9eg'
Running DRC as a precondition to command write_bitstream
INFO: [IP_Flow 19-1839] IP Catalog is up to date.
INFO: [DRC 23-27] Running DRC with 4 threads
/home/ssssspe/FPGA/Vivado/2017.4/bin/loader: line 194:  2570 Killed                  "$RDI_PROG" "$@"
[Tue May 29 04:32:32 2018] impl_1 finished
wait_on_run: Time (s): cpu = 02:45:07 ; elapsed = 03:02:46 . Memory (MB): peak = 7468.555 ; gain = 0.000 ; free physical = 7240 ; free virtual = 11668
problem implementing dynamic region, write_bitstream ERROR
    while executing
"error {problem implementing dynamic region, write_bitstream ERROR}"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 error [list $msg]"
    (procedure "error2file" line 12)
    invoked from within
"error2file $cwd "problem implementing dynamic region, $run_status" "
    (procedure "ocl_util::create_bitstreams_unip" line 112)
    invoked from within
"ocl_util::create_bitstreams_unip $dsa_info $config_info $clk_info"
    (file "/home/ssssspe/song/FPGA/CHaiDNN/design/scripts/kernel/_sds/p0/_vpl/ipi/ipirun.tcl" line 188)
INFO: [Common 17-206] Exiting Vivado at Tue May 29 04:33:42 2018...

Can you help me?

**Comment by VishalX** [comment]
Hi @HelloSongRen,

This is a known issue with SDx 2017.4 which is now fixed with SDx 18.2 release. Please try CHaiDNN-v2 with 18.2.
