### ISSUE TITLE
reVISION platform

### ISSUE THREAD

**Issue by cypox** [Xilinx/CHaiDNN#22]
I am building the project on Linux 16.04 using the zcu102 platform.

I want to know if it is possible to compile the project with a different platform to include HDMI/Camera input?

I want to use this with the reVISION platform.

**Comment by VishalX** [comment]
Hi @cypox,

You can use reVISION platform, but if you are including HDMI/camera modules, make sure that you don't run out of FPGA resources. If you don't need all the accelerator functions, remove them from the build to free up the resources.

**Comment by cypox** [comment]
As for ressources, it is going to be tough since BRAMS are already at 90%. However, the answer was more than enough.

Thanks @VishalX, I will try it.

**Comment by VishalX** [comment]
Closing
