### ISSUE TITLE
New network

### ISSUE THREAD

**Issue by Anjali-iit8** [Xilinx/CHaiDNN#24]
Hi,
Regarding running a new network tutorial. Can I add my own code to the MyNet.cpp file like some opencv functions to add functionality to my network.

Thanks,
Anjali

**Comment by smenon009** [comment]
Hi @Anjali-iit8 
Yes, you can. Pls check out CHai V2 and the software layer plugin feature here: https://github.com/Xilinx/CHaiDNN/blob/master/docs/SOFTWARE_LAYER_PLUGIN.md
