### ISSUE TITLE
Can you provide your train_val.prototxt file

### ISSUE THREAD

**Issue by daichong123** [Xilinx/CHaiDNN#27]
Hello,thanks for the source code you provided. Now I have encountered some problems. I hope to refer to the train_val.prototxt file of your googlenet project.I want to know the difference of your train_val.prototxt and the deploy.prototxt file.Can you provide it? Thank you!

**Comment by smenon009** [comment]
Hi @daichong123 
Pls find the deploy and latest models here: https://github.com/Xilinx/CHaiDNN/blob/master/docs/MODELZOO.md 
Regarding train_val, we have used the one available in public from the Caffe modelzoo.

**Comment by VishalX** [comment]
Closing.
