### ISSUE TITLE
Problems caused by adding "opencv_videoio"

### ISSUE THREAD

**Issue by liyang53719** [Xilinx/CHaiDNN#28]
Hello there
I would like to add the "VideoCapture" function using the opencv library provided here.
I added "videoio.hpp" as follows.

********************************************************************
#if 1//def __SDSCC__
#undef __ARM_NEON__
#undef __ARM_NEON
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/videoio/videoio.hpp>
#define __ARM_NEON__
#define __ARM_NEON
#else
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/videoio.hpp>
#endif
********************************************************************

Added "opencv_videoio" in SDS++Linker->Libraries->Libraries(-l)
But when I compile it cannot be compiled successfully.

********************************************************************
10:09:27 **** Incremental Build of configuration Debug for project CHaiDNN_ly_opencv_o ****
make pre-build main-build 
sdsoc_make_clean Debug
 
Building target: CHaiDNN_ly_opencv_o.elf
Invoking: SDS++ Linker
sds++ -xp param:compiler.skipTimingCheckAndFrequencyScaling=1 -L/home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib -L/home/liyang/Github/xilinx/CHaiDNN/SD_Card/protobuf_arm64/lib --remote_ip_cache /home/liyang/workspace/CHaiDNN/ip_cache -o "CHaiDNN_ly_opencv_o.elf"  ./src/software/xtract/caffe.pb.o ./src/software/xtract/caffe_network_parser.o ./src/software/xtract/hw_settings.o ./src/software/xtract/xgraph.o ./src/software/xtract/xi_funcs.o ./src/software/xtract/xtract_opt.o  ./src/software/swkernels/xi_crop.o ./src/software/swkernels/xi_nms_top.o ./src/software/swkernels/xi_norm_top.o ./src/software/swkernels/xi_permute_top.o ./src/software/swkernels/xi_swsoftmax_top.o  ./src/software/scheduler/xi_scheduler.o ./src/software/scheduler/xi_thread_routines.o ./src/software/scheduler/xi_utils.o  ./src/software/interface/xi_interface.o  ./src/software/init/xi_init.o  ./src/software/include/xchange_structs.o  ./src/software/imageread/xi_input_image.o  ./src/software/example/ssd_ex.o  ./src/software/common/xi_kernels.o  ./src/software/checkers/checkers.o  ./src/software/bufmgmt/xi_buf_mgmt.o  ./src/design/utils/common/dnn_wrapper.o  ./src/design/src/pool/example/pooling_layer_dp_2xio_top.o  ./src/design/src/gemv/example/xi_sgemv_top.o  ./src/design/src/deconv/example/xi_deconv_top.o  ./src/design/src/conv/example/xi_convolution_top.o   -lopencv_core -llzma -ltiff -lpng16 -lz -ljpeg -lopencv_imgproc -lopencv_imgcodecs -ldl -lrt -lwebp -lprotobuf -lopencv_videoio -dmclkid 1  -sds-sys-config a53_linux -sds-proc a53_linux -sds-pf "zcu102"
Validating feature ap_sdsoc
License available for feature ap_sdsoc
Your ap_sdsoc license expires in 4 day(s)
Removing implementation files from previous run
Analyzing object files
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/caffe.pb.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/caffe_network_parser.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/hw_settings.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/xgraph.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/xi_funcs.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/xtract_opt.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_crop.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_nms_top.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_norm_top.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_permute_top.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_swsoftmax_top.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/scheduler/xi_scheduler.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/scheduler/xi_thread_routines.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/scheduler/xi_utils.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/interface/xi_interface.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/init/xi_init.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/include/xchange_structs.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/imageread/xi_input_image.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/example/ssd_ex.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/common/xi_kernels.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/checkers/checkers.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/bufmgmt/xi_buf_mgmt.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/utils/common/dnn_wrapper.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/pool/example/pooling_layer_dp_2xio_top.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/gemv/example/xi_sgemv_top.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/deconv/example/xi_deconv_top.o
... /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/conv/example/xi_convolution_top.o
Using prebuilt hardware
Skipping block diagram (BD), address map, port information and device registration for partition 0
Prepare hardware access API functions
Create accelerator stub functions
Compile hardware access API functions
Compile accelerator stub functions
Enable generation of boot files
Compile hardware access API functions
Link application ELF file
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libgobject-2.0.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found ( Try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libglib-2.0.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found ( Try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libgstreamer-1.0.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found ( Try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libgstapp-1.0.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found ( Try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libgstriff-1.0.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found ( Try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libgstpbutils-1.0.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found ( Try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libv4l1.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libv4l2.so.0, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libavcodec.so.57, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libavformat.so.57, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libavutil.so.55, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libswscale.so.4, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
/home/liyang/soft/xilinx/SDK/2017.4/gnu/aarch64/lin/aarch64-linux/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../.. /../aarch64-linux-gnu/bin/ld: warning: libgphoto2.so.6, needed by /home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
...
...
...
collect2: error: ld returned 1 exit status
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling 'aarch64-linux-gnu-g++     /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/caffe.pb.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/caffe_network_parser.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/hw_settings.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/xgraph.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/xi_funcs.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/xtract/xtract_opt.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_crop.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_nms_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_norm_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_permute_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/swkernels/xi_swsoftmax_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/scheduler/xi_scheduler.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/scheduler/xi_thread_routines.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/scheduler/xi_utils.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/interface/xi_interface.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/init/xi_init.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/include/xchange_structs.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/imageread/xi_input_image.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/example/ssd_ex.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/common/xi_kernels.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/checkers/checkers.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/software/bufmgmt/xi_buf_mgmt.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/utils/common/dnn_wrapper.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/pool/example/pooling_layer_dp_2xio_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/gemv/example/xi_sgemv_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/deconv/example/xi_deconv_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/src/design/src/conv/example/xi_convolution_top.o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/_sds/swstubs/portinfo.o -L/home/liyang/Github/xilinx/CHaiDNN/SD_Card/opencv_arm64/lib -L/home/liyang/Github/xilinx/CHaiDNN/SD_Card/protobuf_arm64/lib -lopencv_core -llzma -ltiff -lpng16 -lz -ljpeg -lopencv_imgproc -lopencv_imgcodecs -ldl -lrt -lwebp -lprotobuf -lopencv_videoio   -L /home/liyang/soft/xilinx/SDx/2017.4/target/aarch64-linux/lib -L/home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/_sds/swstubs -Wl,--start-group  -Wl,--end-group -Wl,--start-group    -lpthread -lsds_lib -lxlnk_stub  -Wl,--end-group -o /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/_sds/swstubs/CHaiDNN_ly_opencv_o.elf'
sds++ log file saved as /home/liyang/workspace/CHaiDNN/CHaiDNN_ly_opencv_o/Debug/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed

makefile:60: recipe for target 'CHaiDNN_ly_opencv_o.elf' failed
********************************************************************

I try to add those libraries in the warning. However, "libgobject-2.0.so.0" was not found in the provided directory
How can I solve this problem?
Is there a problem with the opencv library or is there a problem with my setup?
What compiler is used by this opencv library. If I want to compile the opencv library myself, which compiler should I use?
Aarch64-linux-gnu-g++? (mentioned in the SDSoC error)
Arm-linux-gnueabihf-g++ ? (found in petalinux)

**Comment by VishalX** [comment]
CHaiDNN doesn't provide opencv video_io libs. You have to compile opencv with aarch64-linux-gnu-g++ to get video_io libs.
