### ISSUE TITLE
Need to modify quantization_param in quantized.prototxt file. But can not parse the prototxt file using caffe.Net

### ISSUE THREAD

**Issue by mdamirsohail13** [Xilinx/CHaiDNN#31]
I am making an experiment. I **quantized a model**. It **gives me quantized.prototxt file**. It has an **extra parameter named quantization_param** . So, when **trying to parse** the file using caffe.Net(), it throws an **error** mentioning :
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 66:22: Message type "caffe.LayerParameter" has **no field named "quantization_param"**.

quantization_param looks like -
quantization_param {
    bw_layer_in: 32
    bw_layer_out: 32
    bw_params: 8
    fl_layer_in: 24
    fl_layer_out: 20
    fl_params: 8
  }

How can I access that quantized.prototxt file and modify fields of quantization_param. **Do you have any idea ?** Can you provide **any Python code / Shell script** to do this job. Thanks in Advance

![temp](https://user-images.githubusercontent.com/24891820/41960672-0250ac2a-7a0e-11e8-9600-c245675942fa.png)

**Comment by smenon009** [comment]
hi @mdamirsohail13 
Checkout  the latest CHai(v2), it provides some nifty tools to make this part a little easier for users. 
Quantization & XportDNN: https://github.com/Xilinx/CHaiDNN/blob/master/docs/QUANTIZATION.md 
Setup: https://github.com/Xilinx/CHaiDNN/blob/master/tools/SETUP_TOOLS.md
