### ISSUE TITLE
Error on ZC102 board while executing

### ISSUE THREAD

**Issue by dhruvchamania** [Xilinx/CHaiDNN#32]
libprotobuf FATAL ../../SD_Card/protobuf_arm64/include/google/protobuf/repeated_field.h:1418] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
Aborted

Used the exact code as in https://github.com/Xilinx/CHaiDNN/blob/master/RUN_NEW_NETWORK.md

**Comment by abid-k** [comment]
Hello @dhruvchamania 

We have released CHaiDNN-v2 last week with [better features and performance](https://github.com/Xilinx/CHaiDNN/blob/master/README.md).

Here is the new document on how to [run a new network](https://github.com/Xilinx/CHaiDNN/blob/master/docs/RUN_NEW_NETWORK.md).

Could you please give it a try? Let's know if the above issue still exists.

**Comment by abid-k** [comment]
Closing the issue for now.
