### ISSUE TITLE
Integration error, problem implementing dynamic region

### ISSUE THREAD

**Issue by OnTimeSir** [Xilinx/CHaiDNN#4]
Hi,

I am trying to build CHaiDNN with SDx but I have the issue below：

ERROR: [VPL 60-704] Integration error, problem implementing dynamic region, opt_design ERROR
make: *** [test_alexnet.elf] Error 1
ERROR: [VPL 60-806] Failed to finish platform linker
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling '/home/zhoufanyu/Programes/Xilinx/SDx/2017.4/bin/vpl  --iprepo /home/zhoufanyu/workspace/test_alexnet/Debug/_sds/iprepo/repo  --iprepo /home/zhoufanyu/Programes/Xilinx/SDx/2017.4/data/ip/xilinx  --platform /home/zhoufanyu/Programes/Xilinx/SDx/2017.4/platforms/zcu102/zcu102.xpfm  --temp_dir /home/zhoufanyu/workspace/test_alexnet/Debug/_sds/p0  --output_dir /home/zhoufanyu/workspace/test_alexnet/Debug/_sds/p0/vpl  --input_file /home/zhoufanyu/workspace/test_alexnet/Debug/_sds/p0/.xsd/top.bd.tcl  --target hw   --save_temps  --kernels PoolTop:xiSgemvTop:XiDeconvTop:XiConvolutionTop --webtalk_flag SDSoC  --remote_ip_cache /home/zhoufanyu/workspace/ip_cache --xp "param:compiler.skipTimingCheckAndFrequencyScaling=1" '
sds++ log file saved as /home/zhoufanyu/workspace/test_alexnet/Debug/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed

makefile:60: recipe for target 'test_alexnet.elf' failed

Could anyone help? Thanks.

**Comment by nkpavan** [comment]
Hi

Please re-build the design and if you still face the same issue please send the vivado.log file.

**Comment by Jwy-jump** [comment]
@VishalX ，I rebuilt many times,ERROR: [VPL 60-704] Integration error, One or more synthesis runs failed during dynamic region dcp generation
ERROR: [VPL 60-806] Failed to finish platform linker
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling '/home/jwy/SDx/SDx/2018.2/bin/vpl   --iprepo /home/jwy/workspace/chaindnn/Release/_sds/iprepo/repo  --iprepo /home/jwy/SDx/SDx/2018.2/data/ip/xilinx  --platform /home/jwy/SDx/SDx/2018.2/platforms/zcu102/zcu102.xpfm  --temp_dir /home/jwy/workspace/chaindnn/Release/_sds/p0  --output_dir /home/jwy/workspace/chaindnn/Release/_sds/p0/vpl  --input_file /home/jwy/workspace/chaindnn/Release/_sds/p0/.xsd/top.bd.tcl  --target hw   --save_temps  --kernels PoolTop:XiDeconvTop:XiConvolutionTop:adapter --webtalk_flag SDSoC  --remote_ip_cache /home/jwy/workspace/ip_cache --xp "param:compiler.skipTimingCheckAndFrequencyScaling=1" --xp "vivado_prop:run.impl_1.{STEPS.OPT_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.impl_1.{STEPS.PLACE_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.impl_1.STEPS.PHYS_OPT_DESIGN.IS_ENABLED=1" --xp "vivado_prop:run.impl_1.{STEPS.PHYS_OPT_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.impl_1.{STEPS.ROUTE_DESIGN.ARGS.MORE OPTIONS}={-directive Explore}" --xp "vivado_prop:run.synth_1.{STEPS.SYNTH_DESIGN.TCL.PRE}={/home/jwy/workspace/chaindnn/src/design/conv/scripts/mcps.tcl}" --xp "vivado_prop:run.impl_1.{STEPS.PLACE_DESIGN.TCL.PRE}={/home/jwy/workspace/chaindnn/src/design/conv/scripts/mcps.tcl}" --xp "param:compiler.deleteDefaultReportConfigs=false" '
sds++ log file saved as /home/jwy/workspace/chaindnn/Release/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed
sds++ completed at Sat Jan 12 08:11:15 PST 2019
[sds.log](https://github.com/Xilinx/CHaiDNN/files/2752826/sds.log)
[Uploading chaindnn_Release.build.log…]()

**Comment by tunghoang290780** [comment]
Has anyone solved this problem "ERROR: [VPL 60-704] Integration error, problem implementing dynamic region, write_bitstream ERROR". I did compile ChainDNN with Ubuntu14.10, SDSoC 2018.2 and ZCU102 board but after sync with upstream repo, this error apparently appeared.

**Comment by xindubawukong** [comment]
I have this problem too. I think it may because there's no enough memory.

**Comment by tunghoang290780** [comment]
> I have this problem too. I think it may because there's no enough memory.

Hi @xindubawukong: Do you mean that zc102 board does not have enough SRAM memory?

**Comment by xindubawukong** [comment]
@tunghoang290780 , I mean there's no enough RAM memory on your Ubuntu. This is a possible reason. SDx needs a lot of memory to run. If you are on a 8GB or less memory machine, you can try 16GB or larger.

**Comment by tunghoang290780** [comment]
> @tunghoang290780 , I mean there's no enough RAM memory on your Ubuntu. This is a possible reason. SDx needs a lot of memory to run. If you are on a 8GB or less memory machine, you can try 16GB or larger.

@xindubawukong that is possible due to another reason. I tried with two machines which both have >64GB DRAM.

**Comment by yarenty** [comment]
Have the same issue with another library - xgboots, if you find any solution please share!

**Comment by tunghoang290780** [comment]
@yarenty 
I fixed this
1) Modify xi_conv_config.h
#define XI_BIAS_URAM_EN          0      
#define XI_WTS_URAM_EN          1
#define XI_ISTG_URAM_EN          1
#define XI_OSTG_URAM_EN        1

2) Run command "
make POOL_ENABLE=0 DECONV_ENABLE=0 -j<N> 
where N is the number of cores

**Comment by gitosu67** [comment]
@tunghoang290780 What N?

**Comment by tunghoang290780** [comment]
@Okaymaddy 
The full command is `make POOL_ENABLE=0 DECONV_ENABLE=0 -jN` where N is the number of cores of your machine

**Comment by gitosu67** [comment]
@tunghoang290780 I am receiving some errors when I am trying to build ChaiDNN. I followed your instructions and made the changes in xi_conv_config.h. I am running for zcu104 in SDX 2019.1.
Attached is my error: 
![image](https://user-images.githubusercontent.com/51384676/83692766-9af1d580-a5c2-11ea-8e33-4d7b68b158d9.png)

Any idea how to fix this?

**Comment by tunghoang290780** [comment]
@Okaymaddy I've got failures with SDX > 2019. Last version I was successful is SDSoC 2018.2

**Comment by Okaymaddy** [comment]
@tunghoang290780 I see, I will try it in version 2018.2. Did you try to build for zcu104? Did all the steps mentioned here (https://github.com/Xilinx/CHaiDNN/blob/master/docs/BUILD_USING_SDX_GUI.md)  plus a few changes in xi_conv_top.h was enough to build the project successfully?

**Comment by Okaymaddy** [comment]
@tunghoang290780 Can you tell me what was your machine's RAM and Memory when you were able build ChaiDNN?
