### ISSUE TITLE
About SliceLayer

### ISSUE THREAD

**Issue by chonwhite** [Xilinx/CHaiDNN#5]
Do you have any plan or agenda to support SliceLayer?

**Comment by smenon009** [comment]
Hi @chonwhite,
I hope you are mentioning this: http://caffe.berkeleyvision.org/tutorial/layers/slice.html 
Essentially, it is a data re-grouping functionality resulting in multiple top-blobs for the consumer layers. Will update if we have a plan to support it directly. Currently, it is not supported.  

Also, could you please share your use-case for slice-layer? I have seen in the siamese-network architectures in the past.
Cheers,
Sairam.

**Comment by smenon009** [comment]
Closing.
