### ISSUE TITLE
How could I get the external memory BW usage

### ISSUE THREAD

**Issue by YaoYuxin** [Xilinx/CHaiDNN#59]
I want to get such profile summary for CHaiDNN on zcu102:

https://www.xilinx.com/html_docs/xilinx2018_2/sdaccel_doc/profile-summary-descriptions-snv1504034333315.html.
But how could I get this one? I want to get the DDR BW while executing various networks.

**Comment by nkpavan** [comment]
@YaoYuxin ,

Please post your question in Xilinx SDSoC forums. Closing it.
