### ISSUE TITLE
Ristretto for ssd?

### ISSUE THREAD

**Issue by HelloSongRen** [Xilinx/CHaiDNN#6]
How do you use ristretto to determine the precision parameters for ssd? Can ristretto fine-tune detection models like ssd? Thinks...

**Comment by smenon009** [comment]
Hello,
By Default, Caffe-Ristretto version do not support SSD layers. We will need to add the SSD layers implementations manually to the Ristretto -Caffe and make sure the merged Caffe-Risterrto+SSD code-base does not complain and throw errors while building/ running.  Then, one could use  it to fine-tune/ re-train SSD type networks. CHaiDNN does not expect quantization parameters for SSD specific layers such as permute, normalize, flatten, NMS etc.

**Comment by HelloSongRen** [comment]
Thanks~

**Comment by HelloSongRen** [comment]
Hello, can you share your merged Caffe-Risterrto+SSD code?

**Comment by smenon009** [comment]
Hi @HelloSongRen 
Will check and get back on this.

**Comment by smenon009** [comment]
Hi @HelloSongRen 
We will soon releasing some tools for re-training as well and that will support SSD.
