### ISSUE TITLE
Custom Platform Generation doubts in 5) and 7)

### ISSUE THREAD

**Issue by salcanmor** [Xilinx/CHaiDNN#62]
Hi guys,

I'm trying to build CHaiDNN from source. 

I'm following all the steps and now I'm confusing about step 5 and 7.
I have 3 questions :smile:

`5. Copy zcu102 folder from the <INSTALLATION DIRECTORY>/Xilinx/SDx/2018.2/platforms directory to some working folder. For example, <custom_platform_path>.`

Which directory should be <custom_platform_path ? Maybe the workspace? Maybe the project directory?

Another question.
`7. To build the design with this custom platform, set platform variable to <custom_platform_path>/zcu102 (this path needs to be an absolute path) and set clk_id/dm_clk_id variables to 1 in /design/build/Makefile.`

How can I _**set platform variable to <custom_platform_path>/zcu102**_ ? I don't know how to do that. Can you please help me?

I also went into [/design/build/Makefile](https://github.com/Xilinx/CHaiDNN/blob/master/design/build/Makefile) and I could not find neither **clk_id** nor **dm_clk_id**.

Many thanks in advance.

**Comment by VishalX** [comment]
@salcanmor 

Check below.

5. You need to copy the platforms directory present in your SDx installation and copy it your workspace (can be anywhere in your disk).

7. In Makefile, provide the directory path of the custom platform you've generated. Also, see the line numbers 41 & 42 in [Makefile ](https://github.com/Xilinx/CHaiDNN/blob/master/design/build/Makefile)to see `CLOCK_ID` and `DM_CLOCK_ID`.

Closing this issue.
