### ISSUE TITLE
question regarding Custom Platform Generation

### ISSUE THREAD

**Issue by mazixes** [Xilinx/CHaiDNN#66]
I am trying to run an inference on AVNET UltraZed-EG IO Carrier card which has xczu3eg-sfva625-1-i ultraScale+.

When I run the TCL commands on custom platform generation guide (the first part), comparing to the posted image, I ...

1) don't get pl_ps_irq0 port (should we also add CONFIG.PSU__USE__IRQ0 {1} ?)

2) I get maxihpm0_lpd_aclk and M_AXI_HPM0_LPD ports, which eventually lead to "clk not connected" errors.

Any help is appreciated.

**Comment by VishalX** [comment]
@mazixes,

Have you raised your query on [SDSoC forums](https://forums.xilinx.com/t5/SDSoC-Environment-and-reVISION/bd-p/sdsoc)? That would be a better place to get more details on platform related issues.
