### ISSUE TITLE
Layer placement on FPGAs

### ISSUE THREAD

**Issue by reshkor** [Xilinx/CHaiDNN#68]
Hello,

How does CHaiDNN place the hardware accelerated layers on an FPGA?
Does CPU configure hardware for a single layer acceleration and then re-configures for the next layer processing or all hw accelerated layers are placed on an FPGA?

Thanks in advance.

**Comment by VishalX** [comment]
@reshkor , 

Yes, the CPU configures the parameters for all the layers and pass it on to the design. For layer support, please see [Supported Layers](https://github.com/Xilinx/CHaiDNN/blob/master/docs/SUPPORTED_LAYERS.md).

Thanks.
