### ISSUE TITLE
DepthwiseConvolutionLayer?

### ISSUE THREAD

**Issue by HelloSongRen** [Xilinx/CHaiDNN#7]
Do you have any plan or suggestion to support DepthwiseConvolutionLayer?

**Comment by smenon009** [comment]
Hi @HelloSongRen, 
Yes, we do have plans to support DepthwiseConvolutionLayer and a lot of cool features. Please stay tuned. 
Cheers,
Sairam.

**Comment by HelloSongRen** [comment]
Great! Thank you! @smenon009

**Comment by HelloSongRen** [comment]
Hi @Sairam,
Can you tell me when will it be released? I am trying to add DepthwiseConvolutionLayer but it seems a bit difficult…

**Comment by sairam** [comment]
I think you tagged the wrong user

**Comment by HelloSongRen** [comment]
I am sorry… @sairam
Can you help me? @smenon009

**Comment by smenon009** [comment]
@HelloSongRen The release should be coming up very soon (couple of weeks).
