### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by salcanmor** [Xilinx/CHaiDNN#72]
Hi guys,

You've declared here a variable called **out_count**, and you're not using it.
https://github.com/Xilinx/CHaiDNN/blob/d5bf4142a76c583e7e60b7ec8bb0d4aff0dd31da/software/interface/xi_readwrite_util.cpp#L937

**Comment by VishalX** [comment]
@salcanmor ,

Thanks! We'll make the changes soon. 
Closing.
