### ISSUE TITLE
CHaiDNN can work on Pynq, ZedBoard or Zybo boards?

### ISSUE THREAD

**Issue by saraballeri** [Xilinx/CHaiDNN#75]
HI,

as suggested by the question, it is possible to run the framework on others boards besides Zynq UltraScale+?
And what could be the effort for using CHainDNN on these boards?

Thanks a lot,
Sara

**Comment by saraballeri** [comment]
Hi @VishalX ,
can you help me?
Thanks,
Sara

**Comment by VishalX** [comment]
Please refer to issue #93
