### ISSUE TITLE
Step 16 in instruction for building in SDx IDE is slightly wrong

### ISSUE THREAD

**Issue by lindskogniklas** [Xilinx/CHaiDNN#77]
In https://github.com/Xilinx/CHaiDNN/blob/master/docs/BUILD_USING_SDX_GUI.md, the instruction is to change command to:
`sds++ -sds-hw XiConvolutionTop  <path to design>/src/design/conv/src/xi_convolution_top.cpp -clkid 1 -hls-tcl  <path to design>/src/conv/scripts/config_core.tcl -sds-end`

The following changes is need to make it work:
`<path to design>/src/design/conv/src/xi_convolution_top.cpp` ---> 
`<path to design>/conv/src/xi_convolution_top.cpp`

`<path to design>/src/conv/scripts/config_core.tcl` ---> 
`<path to design>/conv/scripts/config_core.tcl `

**Comment by VishalX** [comment]
Fixed. Thanks! @lindskogniklas.
