### ISSUE TITLE
root (defualt)ZCU102 platform is not seen in the selection

### ISSUE THREAD

**Issue by adu81020799** [Xilinx/CHaiDNN#78]
Hello,
I was trying to generate a custom hardware using the guide here
https://github.com/Xilinx/CHaiDNN/blob/master/docs/CUSTOM_PLATFORM_GEN.md
After I could generate the custom hardware and follow the step the custom platform did get added to the platform selection list but then the old ZCU102 platform is no more seen the selection guide. But in the installation directory-sdx /platforms shows the files for ZCU102. 
How can i get the old the root the platform of ZCU102.
Regards
Adarsh Sawant

**Comment by VishalX** [comment]
@adu81020799 

Which version of SDx you're using?

**Comment by adu81020799** [comment]
sdx 2018.2

**Comment by VishalX** [comment]
@adu81020799,

Did you try the other options on the platform selection dialog?
Try clicking on `Manage Platform Repositories` and select `SDSoc` tab. 

![sdsoc-platforms](https://user-images.githubusercontent.com/36761320/47348561-5d7f5380-d6cf-11e8-889a-70d20b166547.JPG)

**Comment by VishalX** [comment]
Closing. Please reopen if required.
