### ISSUE TITLE
Failed to find dnn_wrapper.cpp file  after using custom platform:

### ISSUE THREAD

**Issue by adu81020799** [Xilinx/CHaiDNN#80]
I have generated a custom platform for the ZCU102 to run inference using faster frequency. While compiling I get the following error even when the files is actually present in the src folder  
Finished building: ../src/software/bufmgmt/xi_buf_mgmt.cpp
 
Building file: ../src/design/wrapper/dnn_wrapper.cpp
Invoking: SDS++ Compiler
sds++ -sds-hw XiConvolutionTop  /home/uncc_embed/workspace/MLDNN/ChaiDNN_Custom/src/design/conv/src/xi_convolution_top.cpp -clkid 1 -hls-tcl  /home/uncc_embed/workspace/MLDNN/ChaiDNN_Custom/src/design/conv/scripts/config_core.tcl -sds-end -D__SDSOC -D__CONV_ENABLE__ -D__DSP48E2__ -D__SYNTHESIS__ -D__POOL_ENABLE__ -D__DECONV_ENABLE__ -Wall -O0 -I"../src" -I/home/uncc_embed/CHaiDNN/SD_Card/opencv/arm64/include -I/home/uncc_embed/CHaiDNN/SD_Card/protobuf/arm64/include -I/home/uncc_embed/CHaiDNN/SD_Card/cblas/arm64/include -I/home/uncc_embed/workspace/MLDNN/CHaiDNN_Custom/src/design/conv/include -I/home/uncc_embed/workspace/MLDNN/CHaiDNN_Custom/src/design/conv/src -I/home/uncc_embed/workspace/MLDNN/CHaiDNN_Custom/src/design/pool/include -I/home/uncc_embed/workspace/MLDNN/CHaiDNN_Custom/src/design/pool/src -I/home/uncc_embed/workspace/MLDNN/CHaiDNN_Custom/src/design/deconv/include -I/home/uncc_embed/workspace/MLDNN/CHaiDNN_Custom/src/design/deconv/src -c -fmessage-length=0 -MT"src/design/wrapper/dnn_wrapper.o" -MMD -MP -MF"src/design/wrapper/dnn_wrapper.d" -MT"src/design/wrapper/dnn_wrapper.o" -o "src/design/wrapper/dnn_wrapper.o" "../src/design/wrapper/dnn_wrapper.cpp" -sds-hw PoolTop pooling_layer_dp_2xio_top.cpp  -clkid 2 -sds-end -sds-hw XiDeconvTop xi_deconv_top.cpp  -files ../src/design/deconv/src/xi_deconv.hpp  -clkid 2 -sds-end -sds-sys-config linux -sds-proc linux -sds-pf "zc702"
Create data motion intermediate representation
/home/uncc_embed/workspace/MLDNN/ChaiDNN_Custom/src/design/wrapper/dnn_wrapper.cpp:18:10: fatal error: 'xi_conv_config.h' file not found
#include "xi_conv_config.h"
         ^
ERROR: [SdsCompiler 83-5005] clang exited with non-zero code processing /home/uncc_embed/workspace/MLDNN/ChaiDNN_Custom/src/design/wrapper/dnn_wrapper.cpp
make: *** [src/design/wrapper/dnn_wrapper.o] Error 1
sds++ log file saved as /home/uncc_embed/workspace/MLDNN/ChaiDNN_Custom/Release/_sds/reports/sds_dnn_wrapper.log
ERROR: [SdsCompiler 83-5004] Build failed

src/design/wrapper/subdir.mk:18: recipe for target 'src/design/wrapper/dnn_wrapper.o' failed

**Comment by VishalX** [comment]
@adu81020799 ,

`dnn_wrapper.cpp` is not able to find the file `xi_conv_config.h`.
Please check that you have added all the include paths in build settings as mentioned in step 19 of [BUILD_USING_SDX_GUI.md](https://github.com/Xilinx/CHaiDNN/blob/master/docs/BUILD_USING_SDX_GUI.md)

**Comment by VishalX** [comment]
@adu81020799,

`/home/uncc_embed/workspace/MLDNN/ChaiDNN_Custom/src/design/wrapper/dnn_wrapper.cpp:18:10: fatal error: 'xi_conv_config.h' file not found`

Please check that you have added all the include paths correctly in build settings.
