### ISSUE TITLE
'main': symbol multiply defined error building CHaiDNN using SDx IDE

### ISSUE THREAD

**Issue by ensafi** [Xilinx/CHaiDNN#9]
Following the [BUILD_USING_SDX_GUI instructions](https://github.com/Xilinx/CHaiDNN/blob/master/BUILD_USING_SDX_GUI.md) and working around issue #3 by making `clock_start` and related variables `static`, I am getting a final link error with `main()` being multiply defined:

ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling '/opt/Xilinx/SDx/2017.4/bin/llvm-link -o /workspace/CHaiDNN/Debug/_sds/.llvm/sds_all.o /workspace/CHaiDNN/Debug/_sds/.llvm/./src/software/xtract/caffe.pb.s ...

**Comment by hpollittsmith** [comment]
I've found that you cannot build all of the applications in SDx at the same time. If you want to build the SSD example, then you should exclude the other applications from the build. For example, in the Project Explorer-->src-->software-->example right-click on alexnet.cpp and in the menu, select Resource Configurations-->Exclude from Build...   Check the "Debug" and "Release" boxes. The alexnet_ex.cpp will be greyed out in the Project Explorer window. Do this for all the example applications (except the one you want to compile).

Note that this will create a elf file with the same name as your project.

**Comment by VishalX** [comment]
Please exclude other example files from the project; Use one example file while building.
