### ISSUE TITLE
CHaiDNN is not using double pumping by default

### ISSUE THREAD

**Issue by salcanmor** [Xilinx/CHaiDNN#91]
To use double pumping, we use a function called __builtin_mac6x2_mac8x1, which uses a double frequency clock called ap_clk_div2.

According to header of XiConvolutionTop function, we can see:
```
#ifdef __SDSVHLS__
				, bool ap_clk_div2 ) {
```
`__SDSVHLS__` symbol depends on `__HLS_SYN__` and none of them are defined by default.

So, how is possible CHaiDNN use double pumping having this configuration ?

**Comment by nkpavan** [comment]
@salcanmor ,

The __HLS_SYN__ flag is defined by Vivado HLS so user need not define that.

**Comment by salcanmor** [comment]
As you can see in the picture below, `__HLS_SYN__` is not defined by default.

![screenshot_20181026_111143](https://user-images.githubusercontent.com/2684107/47557184-5bf09e00-d910-11e8-9dee-eddf36f36c16.png)

**Comment by nkpavan** [comment]
@salcanmor ,
The macro __HLS_SYN__ will be enabled during HLS synthesis and will enable the double-pumping. You can go through the generated RTL and see that the propagation of 2x clock.

**Comment by salcanmor** [comment]
@nkpavan 
Can you please tell me how can I see the RTL ?
Many thanks!

**Comment by nkpavan** [comment]
You can find it at <project_path>/build/_sds/vhls/XiConvolutionTop/solution/impl/
